AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref XrayLayer
        - !Ref JsonpickleLayer
  XrayLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: xray_layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
  JsonpickleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: jsonpickle_layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9